// Wave 2 -- Target Catalog Expansion and Expansion Pilot.
//
// Formal, versioned inventory of the target profiles the mission (section 10) requires the
// expanded target catalog to cover. Counts are deliberately kept at the minimum the mission's own
// gate (section 39) actually checks -- "at least one target exists for this profile" -- rather than
// picking an arbitrary larger number, per the mission's explicit instruction not to choose counts
// just to satisfy an arbitrary figure.

export type TargetProfileCategory = 'offensive' | 'defensive' | 'speed' | 'support' | 'archetype';

export interface TargetProfileRequirement {
  profileId: string;
  category: TargetProfileCategory;
  purpose: string;
  evidenceUse: string;
  minimumRequiredCount: number;
  sourcePolicy: string;
  legalityRequirements: string[];
  idealStatRange: string;
  intendedScenarios: string[];
  intendedBenchmarkUse: string;
  priority: 'critical' | 'high' | 'medium';
  /** Whether this profile has an explicit PASS/FAIL gate in the mission's section 39 checklist. */
  gated: boolean;
}

export const TARGET_PROFILE_REQUIREMENTS_POLICY_ID = 'champions-wave2-target-profile-requirements';
export const TARGET_PROFILE_REQUIREMENTS_POLICY_VERSION = 'wave2-target-profile-requirements-v1';

const legalitySet = ['species eligible (not provisional/blocked)', 'moves/item/ability in real learnset', 'EV total <=510, each 0-252', 'IV each 0-31', '4 distinct moves'];

export const TARGET_PROFILE_REQUIREMENTS: readonly TargetProfileRequirement[] = [
  // ---- OFENSIVOS ----
  { profileId: 'fast-physical-attacker', category: 'offensive', purpose: 'stress-test candidates against a target that outpaces and hits hard physically', evidenceUse: 'speed + damage scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'ranked by calculated Speed among physical-leaning species', legalityRequirements: legalitySet, idealStatRange: 'calculated speed in the top quartile of the eligible pool, atk >= spa', intendedScenarios: ['speed', 'pressure test'], intendedBenchmarkUse: 'offensive speed-tier benchmark', priority: 'high', gated: true },
  { profileId: 'fast-special-attacker', category: 'offensive', purpose: 'stress-test candidates against a target that outpaces and hits hard specially', evidenceUse: 'speed + damage scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'ranked by calculated Speed among special-leaning species', legalityRequirements: legalitySet, idealStatRange: 'calculated speed in the top quartile, spa > atk', intendedScenarios: ['speed', 'pressure test'], intendedBenchmarkUse: 'offensive speed-tier benchmark', priority: 'high', gated: true },
  { profileId: 'bulky-physical-attacker', category: 'offensive', purpose: 'attacker that also survives return hits, testing candidates that rely on a fast knockout', evidenceUse: 'damage + defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'ranked by (atk x physical bulk index)', legalityRequirements: legalitySet, idealStatRange: 'atk and def+hp both above median', intendedScenarios: ['pressure test', 'defensive test'], intendedBenchmarkUse: 'trade-off benchmark', priority: 'medium', gated: false },
  { profileId: 'bulky-special-attacker', category: 'offensive', purpose: 'special attacker that also survives return hits', evidenceUse: 'damage + defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'ranked by (spa x special bulk index)', legalityRequirements: legalitySet, idealStatRange: 'spa and spd+hp both above median', intendedScenarios: ['pressure test', 'defensive test'], intendedBenchmarkUse: 'trade-off benchmark', priority: 'medium', gated: false },
  { profileId: 'mixed-attacker', category: 'offensive', purpose: 'target that threatens through both attacking stats', evidenceUse: 'damage evidence across both move categories', minimumRequiredCount: 1, sourcePolicy: 'ranked by min(atk, spa) among species with both stats above median', legalityRequirements: legalitySet, idealStatRange: 'atk and spa both above median, neither dominant', intendedScenarios: ['pressure test'], intendedBenchmarkUse: 'coverage benchmark', priority: 'medium', gated: false },
  { profileId: 'spread-physical-attacker', category: 'offensive', purpose: 'doubles-relevant spread-move pressure, physical', evidenceUse: 'damage evidence for spread interactions', minimumRequiredCount: 1, sourcePolicy: 'has a real spread-capable physical move in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a (move-driven, not stat-driven)', intendedScenarios: ['pressure test'], intendedBenchmarkUse: 'spread coverage benchmark', priority: 'medium', gated: true },
  { profileId: 'spread-special-attacker', category: 'offensive', purpose: 'doubles-relevant spread-move pressure, special', evidenceUse: 'damage evidence for spread interactions', minimumRequiredCount: 1, sourcePolicy: 'has a real spread-capable special move in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a (move-driven, not stat-driven)', intendedScenarios: ['pressure test'], intendedBenchmarkUse: 'spread coverage benchmark', priority: 'medium', gated: false },
  { profileId: 'priority-attacker', category: 'offensive', purpose: 'tests candidates against a target that can act before a Speed-based order is resolved', evidenceUse: 'speed/priority scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real damaging move with priority > 0', legalityRequirements: legalitySet, idealStatRange: 'n/a (move-driven)', intendedScenarios: ['speed', 'pressure test'], intendedBenchmarkUse: 'priority-interaction benchmark', priority: 'high', gated: true },
  { profileId: 'setup-attacker', category: 'offensive', purpose: 'tests whether a candidate can pressure a target before it sets up a real stat-boosting move', evidenceUse: 'pressure/role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real stat-boosting setup move in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a (move-driven)', intendedScenarios: ['pressure test', 'role execution'], intendedBenchmarkUse: 'setup-denial benchmark', priority: 'medium', gated: false },
  { profileId: 'offensive-pivot', category: 'offensive', purpose: 'tests candidates against a target that can attack and then pivot out', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real pivot move (u-turn/volt-switch/parting-shot/flip-turn family) in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a (move-driven)', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'pivot-interaction benchmark', priority: 'high', gated: true },

  // ---- DEFENSIVOS ----
  { profileId: 'physical-wall', category: 'defensive', purpose: 'resolve TARGET_CATALOG_EXPANSION_REQUIRED: a real, statistically-bulky physical wall', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'highest (calculated HP x calculated Def) physical-bulk index in the eligible pool, EV/nature-boosted, not base-stat-only per mission section 15', legalityRequirements: legalitySet, idealStatRange: 'physical bulk index in the top decile of the eligible pool', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'defensive benchmark', priority: 'critical', gated: true },
  { profileId: 'special-wall', category: 'defensive', purpose: 'resolve TARGET_CATALOG_EXPANSION_REQUIRED: a real, statistically-bulky special wall', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'highest (calculated HP x calculated SpD) special-bulk index in the eligible pool, EV/nature-boosted', legalityRequirements: legalitySet, idealStatRange: 'special bulk index in the top decile', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'defensive benchmark', priority: 'critical', gated: true },
  { profileId: 'mixed-wall', category: 'defensive', purpose: 'bulky-mixed target resisting both attacking categories', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'highest min(physical bulk index, special bulk index)', legalityRequirements: legalitySet, idealStatRange: 'both bulk indices above median simultaneously', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'defensive benchmark', priority: 'high', gated: false },
  { profileId: 'physically-bulky-attacker', category: 'defensive', purpose: 'defensive-leaning attacker able to threaten back', evidenceUse: 'defensive + damage scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'high physical bulk index with atk above median', legalityRequirements: legalitySet, idealStatRange: 'def+hp above median AND atk above median', intendedScenarios: ['defensive test', 'pressure test'], intendedBenchmarkUse: 'trade-off benchmark', priority: 'medium', gated: false },
  { profileId: 'specially-bulky-attacker', category: 'defensive', purpose: 'defensive-leaning attacker able to threaten back specially', evidenceUse: 'defensive + damage scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'high special bulk index with spa above median', legalityRequirements: legalitySet, idealStatRange: 'spd+hp above median AND spa above median', intendedScenarios: ['defensive test', 'pressure test'], intendedBenchmarkUse: 'trade-off benchmark', priority: 'medium', gated: false },
  { profileId: 'recovery-oriented-target', category: 'defensive', purpose: 'sustain-based target for long-game defensive scenarios', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real recovery move (roost/recover/wish/moonlight/morningsun/synthesis/slackoff/softboiled family) in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a (move-driven)', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'sustain benchmark', priority: 'medium', gated: false },
  { profileId: 'resistance-based-target', category: 'defensive', purpose: 'target whose typing resists common attacking types, not just raw stats', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has >=2 real resisted types via the shared type chart', legalityRequirements: legalitySet, idealStatRange: 'n/a (type-driven)', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'resistance benchmark', priority: 'medium', gated: false },
  { profileId: 'immunity-based-target', category: 'defensive', purpose: 'target with a real type immunity to a common attacking type', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real 0x type-chart immunity to at least one type', legalityRequirements: legalitySet, idealStatRange: 'n/a (type-driven)', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'immunity benchmark', priority: 'medium', gated: false },

  // ---- SPEED ----
  { profileId: 'very-fast', category: 'speed', purpose: 'top-of-pool Speed benchmark', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'highest calculated Speed (252 EV, +Spe nature) in the eligible pool', legalityRequirements: legalitySet, idealStatRange: 'top of the calculated-speed distribution', intendedScenarios: ['speed'], intendedBenchmarkUse: 'speed-tier benchmark', priority: 'high', gated: true },
  { profileId: 'fast', category: 'speed', purpose: 'above-median Speed benchmark', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'top-quartile calculated Speed', legalityRequirements: legalitySet, idealStatRange: 'top quartile of calculated speed', intendedScenarios: ['speed'], intendedBenchmarkUse: 'speed-tier benchmark', priority: 'medium', gated: false },
  { profileId: 'medium', category: 'speed', purpose: 'median Speed benchmark', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'closest calculated Speed to the pool median', legalityRequirements: legalitySet, idealStatRange: 'near the median of calculated speed', intendedScenarios: ['speed'], intendedBenchmarkUse: 'speed-tier benchmark', priority: 'medium', gated: false },
  { profileId: 'slow', category: 'speed', purpose: 'resolve part of TARGET_CATALOG_EXPANSION_REQUIRED: a below-median-Speed target', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'bottom-quartile calculated Speed', legalityRequirements: legalitySet, idealStatRange: 'bottom quartile of calculated speed', intendedScenarios: ['speed'], intendedBenchmarkUse: 'speed-tier benchmark', priority: 'high', gated: true },
  { profileId: 'very-slow', category: 'speed', purpose: 'resolve TARGET_CATALOG_EXPANSION_REQUIRED: the genuinely slow target the sentinel catalog lacked (no target had baseSpeed<=60)', evidenceUse: 'speed + Trick Room scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'lowest calculated Speed (0 EV/IV, -Spe nature) in the eligible pool', legalityRequirements: legalitySet, idealStatRange: 'bottom of the calculated-speed distribution', intendedScenarios: ['speed', 'Trick Room active'], intendedBenchmarkUse: 'speed-tier benchmark', priority: 'critical', gated: true },
  { profileId: 'zero-speed-trick-room', category: 'speed', purpose: 'canonical Trick Room abuser benchmark (0 Speed IV/EV, Brave nature)', evidenceUse: 'Trick Room scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'same species as very-slow, built as an explicit 0-Speed-IV/EV set', legalityRequirements: legalitySet, idealStatRange: '0 speed IV, 0 speed EV', intendedScenarios: ['Trick Room active', 'Trick Room inactive'], intendedBenchmarkUse: 'Trick Room benchmark', priority: 'high', gated: true },
  { profileId: 'choice-scarf-benchmark', category: 'speed', purpose: 'tests candidates against a target whose Speed is boosted by a real held item', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'medium-speed species built with a real Choice Scarf item', legalityRequirements: legalitySet, idealStatRange: 'n/a (item-driven)', intendedScenarios: ['speed'], intendedBenchmarkUse: 'item-speed benchmark', priority: 'medium', gated: false },
  { profileId: 'tailwind-benchmark', category: 'speed', purpose: 'tests candidates against a target under an active Tailwind context', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'medium-speed species that legally knows Tailwind', legalityRequirements: legalitySet, idealStatRange: 'n/a (context-driven)', intendedScenarios: ['speed'], intendedBenchmarkUse: 'tailwind-speed benchmark', priority: 'medium', gated: false },
  { profileId: 'weather-speed-benchmark', category: 'speed', purpose: 'tests candidates against a target whose Speed is boosted by weather-linked ability', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'species with a real weather-boosted-Speed ability (chlorophyll/swift-swim/sand-rush/slush-rush)', legalityRequirements: legalitySet, idealStatRange: 'n/a (ability-driven)', intendedScenarios: ['speed'], intendedBenchmarkUse: 'weather-speed benchmark', priority: 'medium', gated: false },

  // ---- SUPORTE ----
  { profileId: 'fake-out', category: 'support', purpose: 'tests candidates against guaranteed first-turn pressure', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has Fake Out in its real learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'disruption benchmark', priority: 'high', gated: true },
  { profileId: 'redirection', category: 'support', purpose: 'tests candidates against Follow Me / Rage Powder redirection', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real redirection move in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'redirection benchmark', priority: 'high', gated: true },
  { profileId: 'screens', category: 'support', purpose: 'tests candidates against damage-reducing screens support', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real screens move in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'screens benchmark', priority: 'medium', gated: false },
  { profileId: 'speed-control', category: 'support', purpose: 'tests candidates against a target providing speed-order manipulation', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real speed-control move (Trick Room/Tailwind/Thunder Wave/Icy Wind/Electroweb/Sticky Web family)', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['speed'], intendedBenchmarkUse: 'speed-control benchmark', priority: 'high', gated: true },
  { profileId: 'tailwind', category: 'support', purpose: 'dedicated Tailwind setter target', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has Tailwind in its real learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['speed'], intendedBenchmarkUse: 'tailwind benchmark', priority: 'high', gated: true },
  { profileId: 'trick-room', category: 'support', purpose: 'dedicated Trick Room setter target', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has Trick Room in its real learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['Trick Room active'], intendedBenchmarkUse: 'trick-room benchmark', priority: 'high', gated: true },
  { profileId: 'weather-setter', category: 'support', purpose: 'dedicated weather-setter target', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real weather-setting move or ability', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['weather active'], intendedBenchmarkUse: 'weather benchmark', priority: 'high', gated: true },
  { profileId: 'terrain-setter', category: 'support', purpose: 'dedicated terrain-setter target', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real terrain-setting move', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['terrain active'], intendedBenchmarkUse: 'terrain benchmark', priority: 'high', gated: true },
  { profileId: 'disruption', category: 'support', purpose: 'target with real disruption tools (Taunt/Encore-adjacent)', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has Taunt or Encore in its real learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'disruption benchmark', priority: 'medium', gated: false },
  { profileId: 'encore', category: 'support', purpose: 'target that can lock a candidate into a committed action', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has Encore in its real learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'disruption benchmark', priority: 'medium', gated: false },
  { profileId: 'taunt', category: 'support', purpose: 'target that can shut down a candidate\'s status/support plan', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has Taunt in its real learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'disruption benchmark', priority: 'medium', gated: false },
  { profileId: 'helping-hand', category: 'support', purpose: 'target that boosts a partner\'s damage output', evidenceUse: 'partner-dependency scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has Helping Hand in its real learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['partner dependency'], intendedBenchmarkUse: 'support benchmark', priority: 'medium', gated: false },
  { profileId: 'pivot', category: 'support', purpose: 'target that can safely reposition via a real pivot move', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real pivot move in its learnset', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'pivot benchmark', priority: 'high', gated: true },
  { profileId: 'recovery-support', category: 'support', purpose: 'support target that also sustains itself', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has a real recovery move alongside a real support move', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'sustain benchmark', priority: 'medium', gated: false },

  // ---- ARCHETYPES (tags carried by targets built for other reasons; not exclusive species) ----
  { profileId: 'balanced', category: 'archetype', purpose: 'archetype tag for targets without a single dominant specialization', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'no single stat/role signal dominant', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['archetype execution'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'hyper-offense', category: 'archetype', purpose: 'archetype tag for targets built purely to apply pressure', evidenceUse: 'pressure-test scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'offensive-EV-spread target with a top-quartile offensive stat', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['pressure test'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'bulky-offense', category: 'archetype', purpose: 'archetype tag for targets that both attack and endure', evidenceUse: 'pressure/defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'shared with physically/specially-bulky-attacker targets', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['pressure test', 'defensive test'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'trick-room-archetype', category: 'archetype', purpose: 'archetype tag for very-slow/zero-speed-trick-room targets', evidenceUse: 'Trick Room scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'shared with the trick-room/very-slow/zero-speed-trick-room targets', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['Trick Room active', 'Trick Room inactive'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'tailwind-archetype', category: 'archetype', purpose: 'archetype tag for tailwind targets', evidenceUse: 'speed scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'shared with the tailwind/tailwind-benchmark targets', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['speed'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'rain', category: 'archetype', purpose: 'archetype tag for Rain-linked weather targets', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has drizzle ability or Rain Dance', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['weather active'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'sun', category: 'archetype', purpose: 'archetype tag for Sun-linked weather targets', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has drought ability or Sunny Day', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['weather active'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'sand', category: 'archetype', purpose: 'archetype tag for Sand-linked weather targets', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has sand-stream ability or Sandstorm', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['weather active'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'snow', category: 'archetype', purpose: 'archetype tag for Snow-linked weather targets', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'has snow-warning ability or Snowscape', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['weather active'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'terrain-offense', category: 'archetype', purpose: 'archetype tag for terrain-linked targets', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'shared with terrain-setter targets', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['terrain active'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'redirection-offense', category: 'archetype', purpose: 'archetype tag for redirection targets', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'shared with redirection targets', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'control', category: 'archetype', purpose: 'archetype tag for disruption/speed-control targets', evidenceUse: 'role-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'shared with speed-control/disruption targets', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['role execution'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'anti-meta', category: 'archetype', purpose: 'archetype tag for resistance/immunity-based targets', evidenceUse: 'defensive scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'shared with resistance-based/immunity-based targets', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['defensive test'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
  { profileId: 'creative', category: 'archetype', purpose: 'archetype tag for targets that do not fit a conventional single category', evidenceUse: 'archetype-execution scenario evidence', minimumRequiredCount: 1, sourcePolicy: 'assigned when a target legitimately carries 3+ unrelated tags', legalityRequirements: legalitySet, idealStatRange: 'n/a', intendedScenarios: ['archetype execution'], intendedBenchmarkUse: 'archetype benchmark', priority: 'medium', gated: false },
] as const;

/** Profiles whose availability is a named, checked gate in the mission's section 39. */
export const GATED_PROFILE_IDS: readonly string[] = TARGET_PROFILE_REQUIREMENTS.filter(p => p.gated).map(p => p.profileId);

export function assertTargetProfileRequirementsConsistency(): void {
  const ids = TARGET_PROFILE_REQUIREMENTS.map(p => p.profileId);
  const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index);
  if (duplicates.length > 0) throw new Error(`TARGET_PROFILE_REQUIREMENTS_DUPLICATE_PROFILE_ID: ${duplicates.join(',')}`);
  for (const profile of TARGET_PROFILE_REQUIREMENTS) {
    if (profile.minimumRequiredCount < 1) throw new Error(`TARGET_PROFILE_REQUIREMENTS_INVALID_COUNT: ${profile.profileId}`);
  }
}

assertTargetProfileRequirementsConsistency();
